import re

with open('migrations/versions/8a7d5911a384_add_goal_phase_2c_1_fields.py', 'r') as f:
    content = f.read()

# Replace upgrade block
upgrade_match = re.search(r'def upgrade\(\) -> None:.*?(?=def downgrade\(\) -> None:)', content, re.DOTALL)
upgrade_body = '''def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_contributions', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('goal_contributions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('goal_contributions', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('goal_contributions', sa.Column('reference', sa.String(length=255), nullable=True))
    
    op.execute("UPDATE goal_contributions SET currency = 'GHS'")
    op.alter_column('goal_contributions', 'currency', nullable=False)
    
    op.create_index(op.f('ix_goal_contributions_account_id'), 'goal_contributions', ['account_id'], unique=False)
    op.create_index(op.f('ix_goal_contributions_reference'), 'goal_contributions', ['reference'], unique=True)
    op.create_index(op.f('ix_goal_contributions_user_id'), 'goal_contributions', ['user_id'], unique=False)
    op.create_foreign_key('fk_goal_contributions_account_id', 'goal_contributions', 'accounts', ['account_id'], ['id'])
    op.create_foreign_key('fk_goal_contributions_user_id', 'goal_contributions', 'users', ['user_id'], ['id'])
    
    op.add_column('goals', sa.Column('locked_amount', sa.Integer(), nullable=True))
    op.add_column('goals', sa.Column('currency', sa.String(length=3), nullable=True))
    op.execute("UPDATE goals SET locked_amount = 0, currency = 'GHS'")
    op.alter_column('goals', 'locked_amount', nullable=False)
    op.alter_column('goals', 'currency', nullable=False)
    # ### end Alembic commands ###

'''
content = content.replace(upgrade_match.group(0), upgrade_body)

# Replace downgrade block
downgrade_match = re.search(r'def downgrade\(\) -> None:.*', content, re.DOTALL)
downgrade_body = '''def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'currency')
    op.drop_column('goals', 'locked_amount')
    op.drop_constraint('fk_goal_contributions_user_id', 'goal_contributions', type_='foreignkey')
    op.drop_constraint('fk_goal_contributions_account_id', 'goal_contributions', type_='foreignkey')
    op.drop_index(op.f('ix_goal_contributions_user_id'), table_name='goal_contributions')
    op.drop_index(op.f('ix_goal_contributions_reference'), table_name='goal_contributions')
    op.drop_index(op.f('ix_goal_contributions_account_id'), table_name='goal_contributions')
    op.drop_column('goal_contributions', 'reference')
    op.drop_column('goal_contributions', 'currency')
    op.drop_column('goal_contributions', 'user_id')
    op.drop_column('goal_contributions', 'account_id')
    # ### end Alembic commands ###
'''
content = content.replace(downgrade_match.group(0), downgrade_body)

with open('migrations/versions/8a7d5911a384_add_goal_phase_2c_1_fields.py', 'w') as f:
    f.write(content)

