from enum import Enum

class DecisionCode(str, Enum):
    ALLOWED = "ALLOWED"
    INVALID_AMOUNT = "INVALID_AMOUNT"
    ACCOUNT_NOT_FOUND = "ACCOUNT_NOT_FOUND"
    ACCOUNT_ACCESS_DENIED = "ACCOUNT_ACCESS_DENIED"
    INSUFFICIENT_AVAILABLE_FUNDS = "INSUFFICIENT_AVAILABLE_FUNDS"
    FUNDS_LOCKED = "FUNDS_LOCKED"
    CONSTRAINT_VIOLATION = "CONSTRAINT_VIOLATION"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    
    # Phase 2C-1
    GOAL_NOT_FOUND = "GOAL_NOT_FOUND"
    GOAL_NOT_OWNED = "GOAL_NOT_OWNED"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    GOAL_ALREADY_ACHIEVED = "GOAL_ALREADY_ACHIEVED"
    CONTRIBUTION_EXCEEDS_REMAINING_TARGET = "CONTRIBUTION_EXCEEDS_REMAINING_TARGET"
    
    # Phase 2C-2
    GOAL_NOT_ACHIEVED = "GOAL_NOT_ACHIEVED"
    GOAL_ALREADY_RELEASED = "GOAL_ALREADY_RELEASED"
    GOAL_LOCK_INTEGRITY_ERROR = "GOAL_LOCK_INTEGRITY_ERROR"

