"""drop goal categories

Revision ID: 00be7747053d
Revises: 6f4204309ea5
Create Date: 2026-09-25 02:31:53.952202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '00be7747053d'
down_revision: Union[str, None] = '6f4204309ea5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_categories_is_system'), table_name='goal_categories')
    op.drop_index(op.f('ix_goal_categories_user_id'), table_name='goal_categories')
    op.drop_constraint('goals_category_id_fkey', 'goals', type_='foreignkey')
    op.drop_column('goals', 'category_id')
    op.drop_table('goal_categories')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('goals_category_id_fkey'), 'goals', 'goal_categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.create_table('goal_categories',
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('icon', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_system', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('goal_categories_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('goal_categories_pkey'))
    )
    op.create_index(op.f('ix_goal_categories_user_id'), 'goal_categories', ['user_id'], unique=False)
    op.create_index(op.f('ix_goal_categories_is_system'), 'goal_categories', ['is_system'], unique=False)
    # ### end Alembic commands ###

