"""add goal categories

Revision ID: 1e8eccf8a26b
Revises: fc72da3e8b2b
Create Date: 2026-09-17 16:39:38.201638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e8eccf8a26b'
down_revision: Union[str, None] = 'fc72da3e8b2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal_categories',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_categories_is_system'), 'goal_categories', ['is_system'], unique=False)
    op.create_index(op.f('ix_goal_categories_user_id'), 'goal_categories', ['user_id'], unique=False)
    op.add_column('goals', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key('goals_category_id_fkey', 'goals', 'goal_categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Seed system categories
    op.execute("""
        INSERT INTO goal_categories (id, name, icon, is_system, created_at, updated_at) VALUES
        (gen_random_uuid(), 'Emergency', 'Shield', true, now(), now()),
        (gen_random_uuid(), 'Home', 'Home', true, now(), now()),
        (gen_random_uuid(), 'Education', 'GraduationCap', true, now(), now()),
        (gen_random_uuid(), 'Health', 'Heart', true, now(), now()),
        (gen_random_uuid(), 'Devices & Tech', 'Laptop', true, now(), now()),
        (gen_random_uuid(), 'Travel', 'Plane', true, now(), now()),
        (gen_random_uuid(), 'Family', 'Users', true, now(), now())
    """)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('goals_category_id_fkey', 'goals', type_='foreignkey')
    op.drop_column('goals', 'category_id')
    op.drop_index(op.f('ix_goal_categories_user_id'), table_name='goal_categories')
    op.drop_index(op.f('ix_goal_categories_is_system'), table_name='goal_categories')
    op.drop_table('goal_categories')
    # ### end Alembic commands ###

