"""block3_money_movement_hub

Revision ID: 57987abcf1a6
Revises: f85bd4e45960
Create Date: 2026-09-28 00:35:45.059658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57987abcf1a6'
down_revision: Union[str, None] = 'f85bd4e45960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('providers',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('supported_rails', sa.Text(), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_providers_code'), 'providers', ['code'], unique=True)
    op.create_table('webhook_events',
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('processing_status', sa.String(length=50), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('resolved_transaction_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("processing_status IN ('RECEIVED','PROCESSING','PROCESSED','DUPLICATE','REJECTED','ERROR')", name='chk_webhook_processing_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_code', 'provider_event_id', name='uq_webhook_events_provider_event')
    )
    op.create_index(op.f('ix_webhook_events_provider_code'), 'webhook_events', ['provider_code'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider_event_id'), 'webhook_events', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider_reference'), 'webhook_events', ['provider_reference'], unique=False)
    op.create_table('provider_attempts',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('provider_code', sa.String(length=50), nullable=False),
    sa.Column('rail', sa.String(length=50), nullable=False),
    sa.Column('operation', sa.String(length=50), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('provider_idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('provider_reference', sa.String(length=255), nullable=True),
    sa.Column('amount_pesewas', sa.Integer(), nullable=False),
    sa.Column('destination_address', sa.String(length=255), nullable=True),
    sa.Column('destination_type', sa.String(length=50), nullable=True),
    sa.Column('request_payload', sa.Text(), nullable=True),
    sa.Column('response_payload', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.String(length=1000), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','DISPATCHED','SUCCEEDED','FAILED','IN_DOUBT')", name='chk_provider_attempt_status'),
    sa.CheckConstraint('amount_pesewas > 0', name='chk_provider_attempt_amount_positive'),
    sa.CheckConstraint('attempt_number > 0', name='chk_provider_attempt_number_positive'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provider_attempts_provider_idempotency_key'), 'provider_attempts', ['provider_idempotency_key'], unique=True)
    op.create_index(op.f('ix_provider_attempts_provider_reference'), 'provider_attempts', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_provider_attempts_transaction_id'), 'provider_attempts', ['transaction_id'], unique=False)
    op.drop_table('provider_requests')
    op.create_table('outbox_events',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('provider_attempt_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('process_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','PROCESSING','DONE','FAILED')", name='chk_outbox_status'),
    sa.ForeignKeyConstraint(['provider_attempt_id'], ['provider_attempts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_events_provider_attempt_id'), 'outbox_events', ['provider_attempt_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_status'), 'outbox_events', ['status'], unique=False)
    op.create_index(op.f('ix_outbox_events_transaction_id'), 'outbox_events', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_transaction_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_status'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_provider_attempt_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_provider_attempts_transaction_id'), table_name='provider_attempts')
    op.drop_index(op.f('ix_provider_attempts_provider_reference'), table_name='provider_attempts')
    op.drop_index(op.f('ix_provider_attempts_provider_idempotency_key'), table_name='provider_attempts')
    op.drop_table('provider_attempts')
    op.drop_index(op.f('ix_webhook_events_provider_reference'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider_event_id'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_provider_code'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index(op.f('ix_providers_code'), table_name='providers')
    op.drop_table('providers')
    # ### end Alembic commands ###

