"""Add transaction metadata, lineage, and category archiving

Revision ID: 63cfdf918b3e
Revises: 1e8eccf8a26b
Create Date: 2026-09-17 21:29:59.103650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63cfdf918b3e'
down_revision: Union[str, None] = '1e8eccf8a26b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal_categories', sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('transactions', sa.Column('funding_source', sa.String(length=100), nullable=True))
    op.add_column('transactions', sa.Column('note', sa.String(length=500), nullable=True))
    op.add_column('transactions', sa.Column('reverses_transaction_id', sa.UUID(), nullable=True))
    op.add_column('transactions', sa.Column('correction_of_transaction_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'transactions', ['reverses_transaction_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'transactions', ['correction_of_transaction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'correction_of_transaction_id')
    op.drop_column('transactions', 'reverses_transaction_id')
    op.drop_column('transactions', 'note')
    op.drop_column('transactions', 'funding_source')
    op.drop_column('goal_categories', 'is_archived')
    # ### end Alembic commands ###

