"""Add icon to goal model

Revision ID: 6f4204309ea5
Revises: 63cfdf918b3e
Create Date: 2026-09-25 01:22:43.782623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f4204309ea5'
down_revision: Union[str, None] = '63cfdf918b3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goals', sa.Column('icon', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'icon')
    # ### end Alembic commands ###

