"""Add Goal Phase 2C-1 fields

Revision ID: 8a7d5911a384
Revises: c93eb04e5411
Create Date: 2026-09-17 00:49:10.883258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7d5911a384'
down_revision: Union[str, None] = 'c93eb04e5411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('goal_contributions', sa.Column('account_id', sa.UUID(), nullable=True))
    op.add_column('goal_contributions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('goal_contributions', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('goal_contributions', sa.Column('reference', sa.String(length=255), nullable=True))
    
    op.execute("UPDATE goal_contributions SET currency = 'GHS'")
    with op.batch_alter_table('goal_contributions', schema=None) as batch_op:
        batch_op.alter_column('currency', nullable=False)
        batch_op.create_index(batch_op.f('ix_goal_contributions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_contributions_reference'), ['reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_goal_contributions_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_goal_contributions_account_id', 'accounts', ['account_id'], ['id'])
        batch_op.create_foreign_key('fk_goal_contributions_user_id', 'users', ['user_id'], ['id'])
    
    op.add_column('goals', sa.Column('locked_amount', sa.Integer(), nullable=True))
    op.add_column('goals', sa.Column('currency', sa.String(length=3), nullable=True))
    op.execute("UPDATE goals SET locked_amount = 0, currency = 'GHS'")
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('locked_amount', nullable=False)
        batch_op.alter_column('currency', nullable=False)
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('goals', 'currency')
    op.drop_column('goals', 'locked_amount')
    op.drop_constraint('fk_goal_contributions_user_id', 'goal_contributions', type_='foreignkey')
    op.drop_constraint('fk_goal_contributions_account_id', 'goal_contributions', type_='foreignkey')
    op.drop_index(op.f('ix_goal_contributions_user_id'), table_name='goal_contributions')
    op.drop_index(op.f('ix_goal_contributions_reference'), table_name='goal_contributions')
    op.drop_index(op.f('ix_goal_contributions_account_id'), table_name='goal_contributions')
    op.drop_column('goal_contributions', 'reference')
    op.drop_column('goal_contributions', 'currency')
    op.drop_column('goal_contributions', 'user_id')
    op.drop_column('goal_contributions', 'account_id')
    # ### end Alembic commands ###
