"""Make goal contributions account and user ids not null

Revision ID: fc72da3e8b2b
Revises: 8a7d5911a384
Create Date: 2026-09-17 01:40:42.235176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc72da3e8b2b'
down_revision: Union[str, None] = '8a7d5911a384'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal_contributions', 'account_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('goal_contributions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('goal_contributions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('goal_contributions', 'account_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###

